name: Helm docs
on:
  push:
    branches:
      - main
jobs:
  helm-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update docs
        run: make docs

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Helm docs updated
          commit_options: '--no-verify --signoff'
          file_pattern: 'chart/*/*.md'
          skip_fetch: true
          skip_checkout: true
