name: Helm lint and docs
on:
  push:
  pull_request:
jobs:
  helm-lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3.5

      - name: Run helm lint
        run: helm lint chart/iam-runtime-infratographer
  helm-docs:
    needs: helm-lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update docs
        run: make docs

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Helm docs updated
          commit_options: '--no-verify --signoff'
          file_pattern: 'chart/*/*.md'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
